version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pip install -r requirements.txt

  build:  
    commands:
      - echo Build phase...

artifacts:
  files:
    - '**/*'